package com.soinve.bpc.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.soinve.bpc.entity.BloodPressure;

import com.soinve.bpc.dao.BloodPressureDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bloodPressureDaoConfig;

    private final BloodPressureDao bloodPressureDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bloodPressureDaoConfig = daoConfigMap.get(BloodPressureDao.class).clone();
        bloodPressureDaoConfig.initIdentityScope(type);

        bloodPressureDao = new BloodPressureDao(bloodPressureDaoConfig, this);

        registerDao(BloodPressure.class, bloodPressureDao);
    }
    
    public void clear() {
        bloodPressureDaoConfig.clearIdentityScope();
    }

    public BloodPressureDao getBloodPressureDao() {
        return bloodPressureDao;
    }

}
